# Generated by Django 6.0.3 on 2026-03-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employerprofile",
            name="contact_person_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
