# Generated by Django 6.0.3 on 2026-03-26 14:12

import apps.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_employerprofile_contact_person_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicantprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="applicantprofile",
            name="linkedin_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="applicantprofile",
            name="location",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="applicantprofile",
            name="portfolio_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="applicantprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_images/applicants/",
                validators=[apps.profiles.models.validate_profile_image],
            ),
        ),
        migrations.AddField(
            model_name="applicantprofile",
            name="resume_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="resumes/",
                validators=[apps.profiles.models.validate_profile_image],
            ),
        ),
    ]
