# Generated by Django 6.0.3 on 2026-03-26 19:17

import apps.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0003_applicantprofile_bio_applicantprofile_linkedin_link_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicantprofile",
            name="resume_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="resumes/",
                validators=[apps.profiles.models.validate_resume_file],
            ),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="company_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
